import Vue from 'vue';
import Vuetify, {
  VApp,
  VNavigationDrawer,
  VContent,
  VContainer,
  VLayout,
  VFlex,
  VForm,
  VSelect,
  VSwitch,
  VMenu,
  VTextField,
  VBtn,
  VAlert,
  VSpacer,
  VDatePicker,
  VList,
  VListItem,
  VListItemTitle,
  VListItemContent,
  VListItemIcon,
  VIcon,
  VAppBar,
  VAppBarNavIcon,
  VToolbarTitle,
  VListGroup,
  VFadeTransition,
  VToolbar,
  VDataTable,
  VPagination
} from 'vuetify/lib';
import { Ripple } from 'vuetify/lib/directives';

Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VContent,
    VContainer,
    VLayout,
    VFlex,
    VForm,
    VSelect,
    VSwitch,
    VMenu,
    VTextField,
    VBtn,
    VAlert,
    VSpacer,
    VDatePicker,
    VList,
    VListItem,
    VListItemTitle,
    VListItemContent,
    VListItemIcon,
    VIcon,
    VAppBar,
    VAppBarNavIcon,
    VToolbarTitle,
    VListGroup,
    VFadeTransition,
    VToolbar,
    VDataTable,
    VPagination
  },
  directives: {
    Ripple,
  },
});
export default new Vuetify({ ...Vuetify });